export default {
  Login: 'Login',
  Logout: 'Logout',
  Applaunch:'Applaunch',
  UpdateProfilePicture: 'UpdateProfilePicture',
  UpdateProfile: 'UpdateProfile',
  UpdateShippingInfo: 'UpdateShippingInfo',
  HideSplash: 'HideSplash',
  ShowSplash: 'ShowSplash',
  HideWelcome: 'HideWelcome',
  ShowWelcome: 'ShowWelcome',
  AddToBasket: 'AddToBasket',
  RemoveFromBasket: 'RemoveFromBasket',
  LoginGuest: 'LoginGuest',
  LogoutGuest: 'LogoutGuest',
  Priceadd:'Priceadd',
  Colouradd:'Colouradd',
  Sizeadd:'Sizeadd',
  Styleadd:'Styleadd',
  Itemadd:'Itemadd',
  Continetadd:'Continetadd',
  CartCount:'CartCount',
  Clearcart:'Clearcart',
  AddToBasketGuest:'AddToBasketGuest',
  RemoveFromBasketGuest:'RemoveFromBasketGuest',
  IncreamentQuantity:'IncreamentQuantity',
  DecreamentQuantity:'DecreamentQuantity',
  ClearBasketGuest:'ClearBasketGuest',
  OrderCount :'OrderCount',
  Warning:'warning'
};
