export default {
  Login: 'Login',
  Logout: 'Logout',
  UpdateProfilePicture: 'UpdateProfilePicture',
  HideSplash: 'HideSplash',
  ShowSplash: 'ShowSplash',
  HideWelcome: 'HideWelcome',
  ShowWelcome: 'ShowWelcome',
  AddToBasket: 'AddToBasket',
  RemoveFromBasket: 'RemoveFromBasket',
  LoginGuest: 'LoginGuest',
  LogoutGuest: 'LogoutGuest',
  Priceadd:'Priceadd',
  Colouradd:'Colouradd',
  Sizeadd:'Sizeadd',
  Styleadd:'Styleadd',
  Itemadd:'Itemadd',
  Continetadd:'Continetadd',
  CartCount:'CartCount',
  Clearcart:'Clearcart'
};
